/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sensorsimulator;

import java.awt.Color;
import sensorsimulator.network.AlarmProtocol;
import sensorsimulator.network.DataPacket;
import sensorsimulator.network.NetworkTrafficLogger;
import sensorsimulator.network.SensorClient;
import sensorsimulator.network.SensorProtocol;
import sensorsimulator.network.SensorServer;
import sensorsimulator.network.client.TCPNetworkClientImpl;
import sensorsimulator.network.client.UDPNetworkClientImpl;
import sensorsimulator.network.server.TCPNetworkServerImpl;
import sensorsimulator.network.server.UDPNetworkServerImpl;

/**
 *
 * @author Z
 */
public class SensorSimulator extends javax.swing.JFrame {
    private SensorServer sensorServer;
    private SensorClient sensorClient;
    
    /**
     * Creates new form SensorSimulator
     */
    public SensorSimulator() {
        initComponents();
        initNetworkService();
        NetworkTrafficLogger.getInstance().initLogTextArea(logTextArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sensorIdLabel = new javax.swing.JLabel();
        sensorIdTextField = new javax.swing.JTextField();
        sensorPortLabel = new javax.swing.JLabel();
        sensorPortTextField = new javax.swing.JTextField();
        sosafeIpLabel = new javax.swing.JLabel();
        sosafeIpTextField = new javax.swing.JTextField();
        sosafePortLabel = new javax.swing.JLabel();
        sosafePortTextField = new javax.swing.JTextField();
        listenButton = new javax.swing.JButton();
        fireButton = new javax.swing.JButton();
        securityButton = new javax.swing.JButton();
        faultButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        logLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        aboutLabel = new javax.swing.JLabel();
        statusDisplayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sensor Simulator");
        setResizable(false);

        sensorIdLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sensorIdLabel.setText("Sensor ID");

        sensorIdTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sensorIdTextField.setText("1");
        sensorIdTextField.setToolTipText("");

        sensorPortLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sensorPortLabel.setText("Sensor Listening Port Number");

        sensorPortTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sensorPortTextField.setText("9505");
        sensorPortTextField.setToolTipText("");

        sosafeIpLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sosafeIpLabel.setText("SoSafe Server IP Address");

        sosafeIpTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sosafeIpTextField.setText("127.0.0.1");
        sosafeIpTextField.setToolTipText("");

        sosafePortLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sosafePortLabel.setText("SoSafe Server Port Number");

        sosafePortTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sosafePortTextField.setText("5925");
        sosafePortTextField.setToolTipText("");

        listenButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listenButton.setText("Listen to SoSafe Server");
        listenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listenButtonActionPerformed(evt);
            }
        });

        fireButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fireButton.setText("Send Fire Alarm");
        fireButton.setToolTipText("");
        fireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireButtonActionPerformed(evt);
            }
        });

        securityButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        securityButton.setText("Send Security Alarm");
        securityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityButtonActionPerformed(evt);
            }
        });

        faultButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        faultButton.setText("Send Fault Alarm");
        faultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faultButtonActionPerformed(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statusLabel.setText("Sensor Status");

        logLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logLabel.setText("Network Traffic Log");

        logTextArea.setEditable(false);
        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane.setViewportView(logTextArea);

        aboutLabel.setText("For Summer 2014 COEN 359 Design Pattern Class Project, Zhe Sun and Hongsen He");

        statusDisplayLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statusDisplayLabel.setForeground(java.awt.Color.blue);
        statusDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusDisplayLabel.setText("No Alarm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aboutLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sensorIdLabel)
                            .addComponent(sosafeIpLabel)
                            .addComponent(sensorPortTextField)
                            .addComponent(sensorPortLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(faultButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fireButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(securityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sensorIdTextField)
                            .addComponent(sosafeIpTextField)
                            .addComponent(sosafePortLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sosafePortTextField)
                            .addComponent(listenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(logLabel)
                                    .addComponent(statusLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(statusDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sensorIdLabel)
                    .addComponent(statusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sensorIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusDisplayLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sensorPortLabel)
                    .addComponent(logLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sensorPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sosafeIpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sosafeIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sosafePortLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sosafePortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(listenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fireButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(securityButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(faultButton)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(jScrollPane))
                .addGap(18, 18, 18)
                .addComponent(aboutLabel)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listenButtonActionPerformed
        // TODO add your handling code here:
        this.sensorServer.listen(Integer.parseInt(sensorPortTextField.getText()));
    }//GEN-LAST:event_listenButtonActionPerformed

    private void fireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireButtonActionPerformed
        // TODO add your handling code here:
        DataPacket packet = new DataPacket();
        byte[] data = AlarmProtocol.generateAlarm(AlarmProtocol.ALARM_TYPE_FIRE, Long.parseLong(sensorIdTextField.getText()), AlarmProtocol.ALARM_MEMO_FIRE);
        packet.setHost(sosafeIpTextField.getText());
        packet.setPort(Integer.parseInt(sosafePortTextField.getText()));
        packet.setData(data);
        this.sensorClient.send(packet);
        statusDisplayLabel.setText("Fire Alarm");
        statusDisplayLabel.setForeground(Color.RED);
    }//GEN-LAST:event_fireButtonActionPerformed

    private void securityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityButtonActionPerformed
        // TODO add your handling code here:
        DataPacket packet = new DataPacket();
        byte[] data = AlarmProtocol.generateAlarm(AlarmProtocol.ALARM_TYPE_SECURITY, Long.parseLong(sensorIdTextField.getText()), AlarmProtocol.ALARM_MEMO_SECURITY);
        packet.setHost(sosafeIpTextField.getText());
        packet.setPort(Integer.parseInt(sosafePortTextField.getText()));
        packet.setData(data);
        this.sensorClient.send(packet);
        statusDisplayLabel.setText("Security Alarm");
        statusDisplayLabel.setForeground(Color.ORANGE);
    }//GEN-LAST:event_securityButtonActionPerformed

    private void faultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faultButtonActionPerformed
        // TODO add your handling code here:
        DataPacket packet = new DataPacket();
        byte[] data = AlarmProtocol.generateAlarm(AlarmProtocol.ALARM_TYPE_FAULT, Long.parseLong(sensorIdTextField.getText()), AlarmProtocol.ALARM_MEMO_FAULT);
        packet.setHost(sosafeIpTextField.getText());
        packet.setPort(Integer.parseInt(sosafePortTextField.getText()));
        packet.setData(data);
        this.sensorClient.send(packet);
        statusDisplayLabel.setText("Fault Alarm");
        statusDisplayLabel.setForeground(Color.YELLOW);
    }//GEN-LAST:event_faultButtonActionPerformed
    
    private void initNetworkService() {
        this.sensorServer = new SensorServer(new TCPNetworkServerImpl()); // Use TCP to listen to SoSafe Server
        //this.sensorClient = new SensorClient(new TCPNetworkClientImpl());
        //this.sensorServer = new SensorServer(new UDPNetworkServerImpl());
        this.sensorClient = new SensorClient(new UDPNetworkClientImpl()); // Use UDP to send to SoSafe Server 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SensorSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SensorSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SensorSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SensorSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SensorSimulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JButton faultButton;
    private javax.swing.JButton fireButton;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton listenButton;
    private javax.swing.JLabel logLabel;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JButton securityButton;
    private javax.swing.JLabel sensorIdLabel;
    private javax.swing.JTextField sensorIdTextField;
    private javax.swing.JLabel sensorPortLabel;
    private javax.swing.JTextField sensorPortTextField;
    private javax.swing.JLabel sosafeIpLabel;
    private javax.swing.JTextField sosafeIpTextField;
    private javax.swing.JLabel sosafePortLabel;
    private javax.swing.JTextField sosafePortTextField;
    private javax.swing.JLabel statusDisplayLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
